services:
  - type: pserv
    name: chronopars-db
    plan: free

  - type: web
    name: chrono-parse
    env: python
    buildCommand: pip install --upgrade pip && pip install -r requirements.txt && python manage.py migrate && python manage.py seed_data && python manage.py collectstatic --noinput
    startCommand: gunicorn chronopars.wsgi:application
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: chronopars-db
          property: connectionString
      - key: DJANGO_SETTINGS_MODULE
        value: chronopars.settings