# Generated by Django 5.2.3 on 2025-07-03 20:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_timetablesource_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timetablesource',
            name='status',
        ),
    ]
