# Generated by Django 5.2.3 on 2025-07-03 21:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_delete_timetableevent'),
    ]

    operations = [
        migrations.RenameField(
            model_name='timetablesource',
            old_name='source_pdf',
            new_name='source_json',
        ),
    ]
