# Generated by Django 5.2.3 on 2025-07-05 16:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_rename_source_pdf_timetablesource_source_json'),
    ]

    operations = [
        migrations.AddField(
            model_name='timetablesource',
            name='events_parsed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='timetablesource',
            name='status',
            field=models.CharField(choices=[('PROCESSING', 'Processing'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='PROCESSING', max_length=10),
        ),
        migrations.AddField(
            model_name='timetablesource',
            name='total_events',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='CourseRegistrationHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_codes', models.TextField()),
                ('display_name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_used', models.DateTimeField(auto_now=True)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.timetablesource')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-last_used'],
            },
        ),
        migrations.CreateModel(
            name='TimetableEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(db_index=True, max_length=10)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('location', models.CharField(max_length=255)),
                ('course_code', models.CharField(db_index=True, max_length=20)),
                ('normalized_code', models.CharField(db_index=True, max_length=20)),
                ('details', models.CharField(blank=True, max_length=100, null=True)),
                ('lecturer', models.CharField(blank=True, max_length=255, null=True)),
                ('source', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='core.timetablesource')),
            ],
            options={
                'indexes': [models.Index(fields=['source', 'normalized_code'], name='core_timeta_source__e9827d_idx'), models.Index(fields=['day', 'start_time'], name='core_timeta_day_32da7c_idx')],
            },
        ),
    ]
