# Generated by Django 5.2.3 on 2025-07-05 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_timetablesource_events_parsed_timetablesource_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseregistrationhistory',
            name='level',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='courseregistrationhistory',
            name='program',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
