# Generated by Django 5.2.3 on 2025-07-05 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_courseregistrationhistory_level_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('student', 'Student'), ('teacher', 'Teacher'), ('staff', 'Staff'), ('other', 'Other')], default='student', help_text='User role in the institution', max_length=20),
        ),
    ]
